apiVersion: v1
kind: ConfigMap
metadata:
  name: vehiserve-config
  labels:
    app: vehiserve
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/vehicle_service?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SERVER_PORT: "8086"
  JWT_EXPIRATION: "36000000"
