# Author: Sridevi Srikumar
apiVersion: v1
kind: Secret
metadata:
  name: vehiserve-secret
  labels:
    app: vehiserve
type: Opaque
data:
  # base64 encoded value of "RMAh@7865"
  SPRING_DATASOURCE_PASSWORD: Uk1BaEA3ODY1
  # base64 encoded value of "RMAh@7865"
  MYSQL_ROOT_PASSWORD: Uk1BaEA3ODY1
  # base64 encoded value of "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  JWT_SECRET: NDA0RTYzNTI2NjU1Nko1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
